### ISSUE TITLE
Enemy 2 - Spiders

### ISSUE THREAD

**Issue by Izabela-Zelek** [Team-MAID/Roguelike#16]
- [x] Create a Spider Object
- [x] Add movement the the spider follows the player within a certain range
- [x] Add health to the spider. 2 health points for now
- [x] Add Colliders on the spiders so that they can collide with the player and room walls
- [x] Destroy spider object after health points are 0 or less
- [x] Make the spider object a prefab

**Comment by PatrickDonnelly** [comment]
Done
