### ISSUE TITLE
Inventory System

### ISSUE THREAD

**Issue by Izabela-Zelek** [Team-MAID/Roguelike#17]
- [x] Look for UI assets
- [x] Draw the Inventory UI

- [x] Store item from the ground in inventory

For inspiration on a simple inventory system: https://www.youtube.com/watch?v=2WnAOV7nHW0

**Comment by Deewens** [comment]
The basic UI is done, I also added some cool sprites, we will probably need to find some other to fits our needs.

The basic system is here and is generalised so it can be used for other entity too like monsters.

I still have some work, I updated the issue description accordingly.

**Comment by Deewens** [comment]
This has been broke into multiple task, see: #38
