### ISSUE TITLE
Enemy 5 - Vampires

### ISSUE THREAD

**Issue by Izabela-Zelek** [Team-MAID/Roguelike#21]

**Comment by Danial-hakim** [comment]
- [ ] Create simple gameObject 
- [ ] Vampire chasing player if player is in range 
- [ ] Create health bar and make it into a slider 
- [ ] Let slider react to vampire health ( The slider whole number should indicate the vampire health) 
- [ ] Attached health bar to vampire 
- [ ] Vampire able to spawn bats every 5 seconds 
- [ ] Update health bar to show vampire current health
