### ISSUE TITLE
Hiding mechanism

### ISSUE THREAD

**Issue by Izabela-Zelek** [Team-MAID/Roguelike#23]

**Comment by Danial-hakim** [comment]
- [ ] Make a gameObject that collide with the player 
- [ ] Have a function that return a bool if player is hiding or not 
- [ ] Let the ghost follow the player when the player is not hiding 
- [ ] The ghost should go back to wonder around when player is hiding

**Comment by Danial-hakim** [comment]
Currently the ghost is static so when the player go in hiding while the ghost is chasing , the ghost would just stop in front on the closet .
