### ISSUE TITLE
Staircase and Level increase

### ISSUE THREAD

**Issue by Izabela-Zelek** [Team-MAID/Roguelike#24]
A staircase is generated randomly in a room and must allow the player to go up one level. When taking the staircase, a new dungeon is generated, and the player cannot go back.
There should be a confirmation message asking the player if he is sure to take the staircase.
The previous level is completely destroyed.

**Comment by Deewens** [comment]
Rebased and merged to master.
Press "U" to use the staircase and generate a new level, when player is overlaping a staircase.
