### ISSUE TITLE
Multiple Room Generation

### ISSUE THREAD

**Issue by Izabela-Zelek** [Team-MAID/Roguelike#36]
The rooms need to be generated procedurally.

Some resources for help:
- https://github.com/marukrap/RoguelikeDevResources#procedural-map-generation
- http://www.roguebasin.com/index.php?title=Basic_BSP_Dungeon_generation 
- https://www.geeksforgeeks.org/tree-traversals-inorder-preorder-and-postorder/
- https://gamedevelopment.tutsplus.com/tutorials/how-to-use-bsp-trees-to-generate-game-maps--gamedev-12268

**Comment by Deewens** [comment]
Rooms are generated procedurally, thanks to a Binary Space Partitioning algorithm and a Binary Tree. For now, only rooms are generated. I still need to generate the hallways:
![image](https://user-images.githubusercontent.com/26287270/197365612-84281b77-102e-46a4-9265-d8a7edf4a2e5.png)

This did not replace the old room generator that we created. I am still using it to generate the actual room and tiles for each "partition" of the BSP.

The current algorithm needs tweaking and is still in a state of "prototype", but works pretty well.

**Comment by Deewens** [comment]
The prototype of room generation is pretty much done. New features will be added to it during the next sprints. I do not close it now as long as it is not completely done.
