### ISSUE TITLE
Update CRC Cards

### ISSUE THREAD

**Issue by Izabela-Zelek** [Team-MAID/Roguelike#44]

**Comment by Danial-hakim** [comment]
- [ ] Game class
- [ ] AudioSystem 
- [ ] Bat_Controller
- [ ] Bat_Manager
- [ ] CameraController
- [ ] Collider
- [ ] EnemyHealthSystem
- [ ] Ghost_Collider
- [ ] Cghost_Controller
- [ ] HealthSystem
- [ ] MenuManager
- [ ] MouseClickHandler
- [ ] Observer
- [ ] PointOfInterest
- [ ] Projectile_Controller
- [ ] ShopDudeScript
- [ ] ShopScript
- [ ] SpiderBehavior
- [ ] SpiderSpawner
- [ ] ratController
- [ ] PlayerController
- [ ] PlayerInventory

**Comment by Danial-hakim** [comment]
CRC card are updated to be at week 5
